type BookTitleMap = Record<number, string>;

const BUKHARI_BOOK_TITLES: BookTitleMap = {
  0: "Introduction",
  1: "Revelation",
  2: "Belief",
  3: "Knowledge",
  4: "Ablutions",
  5: "Bathing",
  6: "Menstrual Periods",
  7: "Tayammum",
  8: "Prayer",
  9: "Prayer Times",
  10: "Call to Prayer",
  11: "Friday Prayer",
  12: "Fear Prayer",
  13: "The Two Festivals",
  14: "Witr Prayer",
  15: "Prayer for Rain",
  16: "Eclipses",
  17: "Prostration During Recitation",
  18: "Shortening the Prayers",
  19: "Night Prayer",
  20: "Virtues of Makkah and Madinah",
  21: "Actions While Praying",
  22: "Forgetfulness in Prayer",
  23: "Funerals",
  24: "Zakat",
  25: "Hajj",
  26: "Umrah",
  27: "Pilgrims Prevented from Completing Hajj",
  28: "Penalty of Hunting During Hajj",
  29: "Virtues of Madinah",
  30: "Fasting",
  31: "Taraweeh",
  32: "Virtues of the Night of Qadr",
  33: "Itikaf",
  34: "Sales and Trade",
  35: "Salam",
  36: "Shufa",
  37: "Hiring",
  38: "Transfer of Debt",
  39: "Kafalah",
  40: "Agency",
  41: "Agriculture",
  42: "Distribution of Water",
  43: "Loans and Bankruptcy",
  44: "Disputes",
  45: "Lost Property",
  46: "Oppressions",
  47: "Partnership",
  48: "Mortgaging",
  49: "Manumission of Slaves",
  50: "Mukatab",
  51: "Gifts",
  52: "Witnesses",
  53: "Peacemaking",
  54: "Conditions",
  55: "Wills",
  56: "Jihad",
  57: "Khumus",
  58: "Jizyah and Treaties",
  59: "Beginning of Creation",
  60: "Prophets",
  61: "Virtues of the Prophet and Companions",
  62: "Companions of the Prophet",
  63: "Merits of the Ansar",
  64: "Military Expeditions",
  65: "Tafsir",
  66: "Virtues of the Quran",
  67: "Marriage",
  68: "Divorce",
  69: "Supporting the Family",
  70: "Food",
  71: "Aqiqah",
  72: "Hunting and Slaughtering",
  73: "Sacrifice",
  74: "Drinks",
  75: "Patients",
  76: "Medicine",
  77: "Dress",
  78: "Good Manners",
  79: "Asking Permission",
  80: "Invocations",
  81: "Softening the Heart",
  82: "Divine Will",
  83: "Oaths and Vows",
  84: "Expiation for Oaths",
  85: "Inheritance",
  86: "Legal Punishments",
  87: "Blood Money",
  88: "Apostates",
  89: "Coercion",
  90: "Legal Stratagems",
  91: "Interpretation of Dreams",
  92: "Afflictions",
  93: "Judgments",
  94: "Wishes",
  95: "Single Narrator Reports",
  96: "Holding Fast to Quran and Sunnah",
  97: "Tawheed",
};

const MUSLIM_BOOK_TITLES: BookTitleMap = {
  0: "Introduction",
  1: "Faith",
  2: "Purification",
  3: "Menstruation",
  4: "Prayer",
  5: "Mosques and Places of Prayer",
  6: "Prayer of Travellers",
  7: "Friday Prayer",
  8: "Eid Prayer",
  9: "Prayer for Rain",
  10: "Eclipse Prayer",
  11: "Funeral Prayer",
  12: "Zakat",
  13: "Fasting",
  14: "Itikaf",
  15: "Hajj",
  16: "Marriage",
  17: "Suckling",
  18: "Divorce",
  19: "Lian",
  20: "Emancipating Slaves",
  21: "Transactions",
  22: "Musaqah",
  23: "Inheritance",
  24: "Gifts",
  25: "Wills",
  26: "Vows",
  27: "Oaths",
  28: "Oaths, Retaliation, and Blood Money",
  29: "Legal Punishments",
  30: "Judicial Decisions",
  31: "Lost Property",
  32: "Jihad and Expeditions",
  33: "Government",
  34: "Hunting and Slaughter",
  35: "Sacrifices",
  36: "Drinks",
  37: "Clothing and Adornment",
  38: "Manners",
  39: "Greetings",
  40: "Correct Words",
  41: "Poetry",
  42: "Dreams",
  43: "Virtues",
  44: "Merits of the Companions",
  45: "Virtue and Kinship",
  46: "Destiny",
  47: "Knowledge",
  48: "Remembrance and Supplication",
  49: "Softening the Heart",
  50: "Repentance",
  51: "Hypocrites",
  52: "Day of Judgment, Paradise, and Hell",
  53: "Paradise",
  54: "Tribulations and Last Hour Signs",
  55: "Zuhd and Heart Softening",
  56: "Tafsir",
};

const BOOK_TITLES_BY_COLLECTION: Record<string, BookTitleMap> = {
  "sahih-bukhari": BUKHARI_BOOK_TITLES,
  "sahih-muslim": MUSLIM_BOOK_TITLES,
};

export function getCanonicalBookTitle(
  collectionSlug: string | null | undefined,
  bookNumber: number | null | undefined,
  databaseTitle?: string | null,
): string {
  const trimmedDatabaseTitle = databaseTitle?.trim();
  if (trimmedDatabaseTitle && !/^book\s+\d+$/i.test(trimmedDatabaseTitle)) {
    return trimmedDatabaseTitle;
  }

  if (bookNumber == null) return trimmedDatabaseTitle || "Book";
  return BOOK_TITLES_BY_COLLECTION[collectionSlug ?? ""]?.[bookNumber] ?? `Book ${bookNumber}`;
}
