import React from 'react';
import { View, Text, StyleSheet, ScrollView, Linking, Pressable } from 'react-native';
import { Stack } from 'expo-router';
import { SPACING, FONT_SIZES, BORDER_RADIUS, getColors } from '@/lib/styles/colors';
import { FONT_FAMILY } from '@/constants/theme';
import { useTheme } from '@/lib/theme/ThemeProvider';
import { SettingsSection } from '@/components/settings/SettingsSection';

const COLLECTIONS = [
  { name: 'Sahih al-Bukhari', compiler: 'Imam Muhammad al-Bukhari (810–870 CE)' },
  { name: 'Sahih Muslim', compiler: 'Imam Muslim ibn al-Hajjaj (815–875 CE)' },
  { name: 'Sunan Abu Dawud', compiler: 'Imam Abu Dawud as-Sijistani (817–889 CE)' },
  { name: 'Jami at-Tirmidhi', compiler: 'Imam Muhammad at-Tirmidhi (824–892 CE)' },
  { name: "Sunan an-Nasa'i", compiler: "Imam Ahmad an-Nasa'i (829–915 CE)" },
  { name: 'Sunan Ibn Majah', compiler: 'Imam Muhammad ibn Majah (824–887 CE)' },
  { name: 'Muwatta Malik', compiler: 'Imam Malik ibn Anas (711–795 CE)' },
  { name: 'Musnad Ahmad', compiler: 'Imam Ahmad ibn Hanbal (780–855 CE)' },
];

export default function CreditsScreen() {
  const { isDark } = useTheme();
  const colors = getColors(isDark);

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <Stack.Screen
        options={{
          title: 'Credits & Sources',
          headerShown: true,
          headerBackTitle: 'Settings',
          headerStyle: { backgroundColor: colors.card },
          headerTintColor: colors.emeraldMid,
          headerShadowVisible: false,
        }}
      />

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.header}>
          <Text style={[styles.headerTitle, { color: colors.bronzeText }]}>Credits & Sources</Text>
          <Text style={[styles.headerSubtitle, { color: colors.mutedText }]}>
            Where the content in Authentic Hadith comes from.
          </Text>
        </View>

        <SettingsSection title="Hadith Collections">
          <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
            {COLLECTIONS.map((c, i) => (
              <View
                key={c.name}
                style={[
                  styles.row,
                  i < COLLECTIONS.length - 1 && { borderBottomColor: colors.borderSubtle, borderBottomWidth: StyleSheet.hairlineWidth },
                ]}
              >
                <Text style={[styles.collectionName, { color: colors.bronzeText }]}>{c.name}</Text>
                <Text style={[styles.collectionMeta, { color: colors.mutedText }]}>{c.compiler}</Text>
              </View>
            ))}
            <Text style={[styles.cardFootnote, { color: colors.mutedText }]}>
              The original Arabic texts are public-domain scholarly works compiled by recognized
              classical scholars.
            </Text>
          </View>
        </SettingsSection>

        <SettingsSection title="English Translations">
          <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <Text style={[styles.placeholderText, { color: colors.bronzeText }]}>
              English translations and Arabic text are sourced from{' '}
              <Pressable onPress={() => Linking.openURL('https://sunnah.com')}>
                <Text style={[styles.link, { color: colors.emeraldMid }]}>sunnah.com</Text>
              </Pressable>
              {' '}under their public usage terms.
            </Text>
            <Text style={[styles.placeholderHint, { color: colors.mutedText }]}>
              Visit sunnah.com for the canonical text, grading methodology, and per-translator
              attribution. Translations are interpretive by nature; for precise religious meaning,
              consult the original Arabic and a qualified scholar.
            </Text>
          </View>
        </SettingsSection>

        <SettingsSection title="AI Assistant">
          <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <Text style={[styles.bodyText, { color: colors.bronzeText }]}>
              AI summaries and Assistant responses are generated by a third-party large language
              model under a system prompt focused on authentic hadith. AI output is not reviewed by
              a scholar before display.
            </Text>
            <Text style={[styles.bodyFootnote, { color: colors.mutedText }]}>
              AI guidance only. For religious rulings, consult a qualified scholar.
            </Text>
          </View>
        </SettingsSection>

        <SettingsSection title="Acknowledgements">
          <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <Text style={[styles.bodyText, { color: colors.bronzeText }]}>
              Built with care for the Muslim ummah by byRed LLC, San Diego, California.
            </Text>
          </View>
        </SettingsSection>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollView: { flex: 1 },
  scrollContent: { padding: SPACING.md },
  header: { marginBottom: SPACING.lg },
  headerTitle: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZES.xxxl, fontWeight: '700', marginBottom: SPACING.xs },
  headerSubtitle: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZES.base },
  card: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.md,
  },
  row: {
    paddingVertical: SPACING.sm,
  },
  collectionName: { fontFamily: FONT_FAMILY.heading, fontSize: FONT_SIZES.base, fontWeight: '600' },
  collectionMeta: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZES.sm, marginTop: 2 },
  cardFootnote: {
    fontSize: FONT_SIZES.xs,
    fontStyle: 'italic',
    marginTop: SPACING.sm,
  },
  placeholderText: { fontSize: FONT_SIZES.base, fontWeight: '600', marginBottom: SPACING.xs },
  placeholderHint: { fontSize: FONT_SIZES.sm, lineHeight: 20 },
  link: { textDecorationLine: 'underline' },
  bodyText: { fontSize: FONT_SIZES.base, lineHeight: 22 },
  bodyFootnote: { fontSize: FONT_SIZES.xs, fontStyle: 'italic', marginTop: SPACING.sm },
});
